import 'conventional_commit.dart';
import 'release.dart';

const _header =
    '# Changelog\n\n'
    'Generated by `tool/bump_version.dart` from Conventional Commit history '
    '— do not hand-edit.\n';

const _breaking = 'Breaking changes';
const _other = 'Other';

const Map<CommitType, String> _headings = {
  CommitType.feat: 'Added',
  CommitType.fix: 'Fixed',
  CommitType.perf: 'Changed',
};

/// Order of the sections inside a release.
const List<String> _order = [_breaking, 'Added', 'Fixed', 'Changed', _other];

String _heading(ReleaseNote note) =>
    note.breaking ? _breaking : _headings[note.type] ?? _other;

String _line(ReleaseNote note) =>
    note.scope == null ? note.subject : '**${note.scope}:** ${note.subject}';

/// One release as markdown, e.g. for a dry run or a GitHub release body.
String renderRelease(Release release) {
  final byHeading = <String, List<String>>{};
  for (final note in release.notes) {
    (byHeading[_heading(note)] ??= []).add(_line(note));
  }

  final buffer = StringBuffer('## v${release.version} - ${release.date}\n');
  for (final heading in _order) {
    final lines = byHeading[heading];
    if (lines == null) continue;
    buffer.write('\n### $heading\n\n');
    for (final line in lines) {
      buffer.writeln('- $line');
    }
  }
  return buffer.toString();
}

/// The whole `CHANGELOG.md`, newest release first.
String renderChangelog(List<Release> releases) =>
    [_header, ...releases.map(renderRelease)].join('\n');
