import 'package:flutter/widgets.dart';
import 'package:go_router/go_router.dart';

import '../../features/auth/presentation/pages/sign_in_page.dart';
import '../../features/changelog/presentation/pages/changelog_page.dart';
import '../../features/inbox/presentation/pages/inbox_page.dart';
import '../../features/notices/presentation/pages/notice_compose_page.dart';
import '../../features/orders/presentation/pages/add_debtor_page.dart';
import '../../features/orders/presentation/pages/balance_page.dart';
import '../../features/orders/presentation/pages/counterpart_page.dart';
import '../../features/orders/presentation/pages/edit_order_page.dart';
import '../../features/orders/presentation/pages/order_detail_page.dart';
import '../../features/orders/presentation/pages/order_form_page.dart';
import '../../features/orders/presentation/pages/orders_page.dart';
import '../../features/orders/presentation/pages/pay_page.dart';
import '../../features/orders/presentation/pages/payment_page.dart';
import '../../features/teams/presentation/pages/create_team_page.dart';
import '../../features/teams/presentation/pages/join_team_page.dart';
import '../../features/teams/presentation/pages/payout_method_page.dart';
import '../../features/teams/presentation/pages/team_detail_page.dart';
import '../../ui/navigation/app_transition_page.dart';
import '../gallery/gallery_page.dart';
import '../settings/appearance_page.dart';
import '../settings/settings_page.dart';
import '../shell/app_shell.dart';
import 'back_navigation.dart';

part 'app_routes.g.dart';
part 'routes/add_debtor_route.dart';
part 'routes/app_shell_route.dart';
part 'routes/appearance_route.dart';
part 'routes/changelog_route.dart';
part 'routes/counterpart_route.dart';
part 'routes/create_team_route.dart';
part 'routes/edit_order_route.dart';
part 'routes/gallery_route.dart';
part 'routes/home_branch.dart';
part 'routes/home_route.dart';
part 'routes/inbox_branch.dart';
part 'routes/inbox_route.dart';
part 'routes/join_team_route.dart';
part 'routes/new_order_route.dart';
part 'routes/notice_route.dart';
part 'routes/order_detail_route.dart';
part 'routes/orders_branch.dart';
part 'routes/orders_route.dart';
part 'routes/pay_route.dart';
part 'routes/payment_route.dart';
part 'routes/payout_setup_route.dart';
part 'routes/settings_branch.dart';
part 'routes/settings_route.dart';
part 'routes/sign_in_route.dart';
part 'routes/team_detail_route.dart';

/// Public so the auth redirect can recognise the sign-in screen.
const signInPath = '/iniciar-sesion';
